name: tailwind_attributes
description: Tailwind Attributes.
version: 1.0.0
repository: https://github.com/rIIh/tailwind-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
