name: tailwind_generator
description: A Tailwind Code generator
version: 1.0.0
repository: https://github.com/rIIh/tailwind-flutter

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.5.0
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

executables:
  tailwind_generator:
